language: node_js
node_js:
  - v10
  - v9
  - v8
  - v6

before_install:
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
- npm install -g greenkeeper-lockfile
install: npm install

before_script: greenkeeper-lockfile-update
script: npm run test
after_script:
- greenkeeper-lockfile-upload
- cat ./coverage/lcov.info | coveralls
